services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: midas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.26-community
    container_name: midas-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP Web Console
      - "7687:7687" # Bolt binary protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  postgres_data:
  neo4j_data:
  neo4j_import:
  neo4j_plugins:
