"""Consolidated PostgreSQL & pgvector connector — 하위 호환 facade.

실제 구현은 도메인별 레포지토리(shared.database.repositories.*)로 분리되었다. 이 모듈은
기존 `from shared.database.connector import X` 임포트가 그대로 동작하도록 레포지토리 함수를
재노출하기만 한다. **새 코드는 repositories 하위 모듈에서 직접 임포트하라.**
"""

from shared.database.repositories import (  # noqa: F401
    apply_schema,
    bulk_upsert_emb_passages,
    bulk_upsert_emb_queries,
    bulk_upsert_emb_triplets,
    bulk_upsert_market_snapshots,
    bulk_upsert_portfolios,
    bulk_upsert_users,
    db_cursor,
    delete_chat_session,
    delete_checkpoint_thread,
    get_all_tax_rules,
    get_connection,
    get_latest_market_snapshots,
    get_last_ingest_time,
    get_latest_market_value,
    get_market_history,
    get_portfolios_by_user_uuid,
    get_user_by_uuid,
    list_chat_sessions,
    list_checkpoint_threads,
    list_emb_sources,
    list_users,
    search_similar_passages_db,
    search_similar_personas_db,
    upsert_chat_session,
    upsert_market_snapshot,
    upsert_user,
)

__all__ = [
    "apply_schema",
    "bulk_upsert_emb_passages",
    "bulk_upsert_emb_queries",
    "bulk_upsert_emb_triplets",
    "bulk_upsert_market_snapshots",
    "bulk_upsert_portfolios",
    "bulk_upsert_users",
    "db_cursor",
    "delete_chat_session",
    "delete_checkpoint_thread",
    "get_all_tax_rules",
    "get_connection",
    "get_latest_market_snapshots",
    "get_last_ingest_time",
    "get_latest_market_value",
    "get_market_history",
    "get_portfolios_by_user_uuid",
    "get_user_by_uuid",
    "list_chat_sessions",
    "list_checkpoint_threads",
    "list_emb_sources",
    "list_users",
    "search_similar_passages_db",
    "search_similar_personas_db",
    "upsert_chat_session",
    "upsert_market_snapshot",
    "upsert_user",
]
