"""Consolidated initial schema

Revision ID: d93ff1c5811e
Revises: None
Create Date: 2026-05-28 20:34:33.379312

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd93ff1c5811e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_references_category'), table_name='legal_references')
    op.drop_index(op.f('idx_macro_embedding_hnsw'), table_name='macro_indicators', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.drop_index(op.f('idx_macro_name_date'), table_name='macro_indicators')
    op.drop_constraint(op.f('uq_macro_indicator'), 'macro_indicators', type_='unique')
    op.drop_index(op.f('ix_market_snapshots_date'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_type_key'), table_name='market_snapshots')
    op.drop_constraint(op.f('uq_market_snapshots_key'), 'market_snapshots', type_='unique')
    op.alter_column('news_embeddings', 'language',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'ko'::bpchar"))
    op.drop_index(op.f('idx_news_embedding_hnsw'), table_name='news_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_news_published_category'), table_name='news_embeddings')
    op.drop_index(op.f('idx_persona_embedding_hnsw'), table_name='persona_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('portfolio_items', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'KRW'::bpchar"))
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('idx_strategy_embedding_hnsw'), table_name='strategy_docs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_strategy_type'), table_name='strategy_docs')
    op.drop_index(op.f('ix_tax_rules_asset_income'), table_name='tax_rules')
    op.drop_constraint(op.f('uq_tax_rules_key'), 'tax_rules', type_='unique')
    op.drop_index(op.f('ix_users_age_aggressiveness'), table_name='users')
    op.drop_index(op.f('ix_users_total_amount'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_total_amount'), 'users', ['total_amount'], unique=False)
    op.create_index(op.f('ix_users_age_aggressiveness'), 'users', ['age', 'aggressiveness'], unique=False)
    op.create_unique_constraint(op.f('uq_tax_rules_key'), 'tax_rules', ['asset_type', 'income_type', 'min_amount', 'max_amount', 'effective_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tax_rules_asset_income'), 'tax_rules', ['asset_type', 'income_type', 'effective_date'], unique=False)
    op.create_index(op.f('idx_strategy_type'), 'strategy_docs', ['strategy_type', sa.literal_column('published_year DESC')], unique=False)
    op.create_index(op.f('idx_strategy_embedding_hnsw'), 'strategy_docs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.alter_column('portfolio_items', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'KRW'::bpchar"))
    op.create_index(op.f('idx_persona_embedding_hnsw'), 'persona_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_news_published_category'), 'news_embeddings', [sa.literal_column('published_at DESC'), 'category'], unique=False)
    op.create_index(op.f('idx_news_embedding_hnsw'), 'news_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('news_embeddings', 'language',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'ko'::bpchar"))
    op.create_unique_constraint(op.f('uq_market_snapshots_key'), 'market_snapshots', ['snapshot_date', 'data_type', 'sub_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_market_snapshots_type_key'), 'market_snapshots', ['data_type', 'sub_key', sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_index(op.f('ix_market_snapshots_date'), 'market_snapshots', [sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_unique_constraint(op.f('uq_macro_indicator'), 'macro_indicators', ['indicator_name', 'indicator_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_macro_name_date'), 'macro_indicators', ['indicator_name', sa.literal_column('indicator_date DESC')], unique=False)
    op.create_index(op.f('idx_macro_embedding_hnsw'), 'macro_indicators', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.create_index(op.f('ix_legal_references_category'), 'legal_references', ['asset_category'], unique=False)
    # ### end Alembic commands ###
